# spring.application.name=socMediaAPI

# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=jdbc:mariadb://localhost:3306/socialmedia_db
# spring.datasource.username=root
# spring.datasource.password=root
# spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/socialmedia_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      '[hibernate.format_sql]': false
      hibernate:
        jdbc:
          lob:
            '[non_contextual_creation]': true
        dialect: org.hibernate.dialect.MariaDBDialect


    
